### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by pauledwardmitchell** [pauledwardmitchell/marvl3#250]
We need a basic "hey that page doesn't exist" page with a link back to the main page, instead of this page:

![Screen Shot 2019-03-20 at 1 51 15 PM](https://user-images.githubusercontent.com/19398192/54707363-48401100-4b17-11e9-9050-cf7dbc7e229a.png)

**Comment by scttnlsn** [comment]
@pauledwardmitchell Anything in particular for this?  It's just a matter of editing `public/404.html` (unless you need any dynamic content)

**Comment by pauledwardmitchell** [comment]
@scttnlsn I am thinking two things:
1. User hits the 404 page instead of this rails error page (seen above)
2. There is a link that will take them back to the home page.

**Comment by scttnlsn** [comment]
@pauledwardmitchell That screenshot is the Rails 404 page (`public/404.html`).  I added a link to the home page in PR #259.  Let me know if there are any additional changes you'd like made.

**Comment by pauledwardmitchell** [comment]
@scttnlsn Thanks for clarifying that.  What you did looks great.  I'll merge these asap.
